### ISSUE TITLE
positioning issues with multiple monitors on linux

### ISSUE THREAD

**Issue by tgbugs** [alex-hhh/gui-widget-mixins#3]
I am encountering an issue with tooltip positioning when there are multiple monitors.
- Gentoo Linux.
- Nvidia drivers with TwinView enabled.
- My primary monitor is to the right of my secondary monitor.

If I had to guess the issue is that TwinView causes the monitors to present as a single virtual monitor to X11 but the Racket gui implementation is too smart for its own good and somehow gets the inset values despite the fact that they are actually irrelevant in this case.

My current fix is to call `(get-display-left-top-inset #:monitor 1)` so that the left most monitor is selected which makes the offsets zero, however that is not a real solution.

https://github.com/alex-hhh/gui-widget-mixins/blob/c7edc4408d9852fe16441bc5b539b1643db398c1/private/tooltip-mixin.rkt#L84

Without trying to dig any further into the details of exactly what is going wrong, my question is whether the offsets are needed or required at all. It seems that even in dual monitor setups they shouldn't be needed. Are there other multiple monitor configurations where they are known to  be needed? Shouldn't the event coordinates be in the same space as the tooltip coordinates and thus not need to be adjusted?

**Comment by alex-hhh** [comment]
On windows, my primary monitor is also to the right of the secondary one, but `get-display-left-top-inset` still works as expected, with the secondary monitor having negative coordinates for the "left top" corner:

```racket
> (require racket/gui)
> (get-display-left-top-inset #:monitor 0)
0
0
> (get-display-left-top-inset #:monitor 1)
-1920
0
> 
```

The call to `get-display-left-top-inset` exists because, on MacOS, there is a difference between the coordinate system used by `client->screen` and `move`, as explained [here](https://docs.racket-lang.org/gui/window___.html?q=client-%3Escreen#%28meth._%28%28%28lib._mred%2Fmain..rkt%29._window~3c~25~3e%29._client-~3escreen%29%29):

> On Mac OS, the screen coordinates start with (0, 0) at the upper left of the menu bar. In contrast, move in top-level-window<%> considers (0, 0) to be below the menu bar.

I have no way to verify this, as I am not using MacOS.

I am also confused about the TwinView configuration.  In [the TwinView description](http://http.download.nvidia.com/XFree86/Linux-x86/1.0-8178/README/appendix-g.html) it indicates that the functionality presents a single display to the rest of the system, so your system should have only one monitor and the call `(get-display-left-top-inset #:monitor 1)` should return `#f`, since there is no second monitor, as far as the rest of the system is concerned...

**Comment by tgbugs** [comment]
I will look into what is going on with TwinView. The key difference I see is that my monitor 0 has the negative offsets, but there is no way for monitor 1 to be used to generate the offsets. I only have remote access to a macos machine at the moment, when I get physical access again I can test.
```racket
> (require racket/gui)
> (get-display-left-top-inset #:monitor 0)
-1200
-370
> (get-display-left-top-inset #:monitor 1)
0
0
> 
```

Based on both our results it seems that the offsets should probably not be part of the calculations since . If you set `#:monitor 1` on your setup I'm guessing you would be able to replicate what I'm seeing.

edit: I'm going to put together a small test program that we can use as a survey on the Racket slack channel where I assume we can find someone who is running macos with multiple monitors.

**Comment by tgbugs** [comment]
This has been determined to be a bug in `(get-display-left-top-inset #:monitor 0)` since the behavior does not match the [docs](https://docs.racket-lang.org/gui/Windowing_Functions.html#%28def._%28%28lib._mred%2Fmain..rkt%29._get-display-left-top-inset%29%29).

**Comment by alex-hhh** [comment]
I am going to reopen this issue: regardless of where the root cause of this issue is, I think this package needs to account for it, I just wanted to better understand the actual issue, before attempting the fix.

... it may also be that the fix for racket/gui#223 is just a documentation update...

As for the fix, it seems that we could apply this offset only on MacOS platforms...

**Comment by tgbugs** [comment]
> As for the fix, it seems that we could apply this offset only on MacOS platforms...

This seems like a good solution.

**Comment by alex-hhh** [comment]
I made some changes on the "ah/macos" branch, which should address this.  Can you please try them out? (there are other changes there, as I am attempting to fix other bugs as well).

https://github.com/alex-hhh/gui-widget-mixins/tree/ah/macos

**Comment by tgbugs** [comment]
The fix works for me.
